name: Deploy Backend

on:
  push:
    branches: [ backend_jwt ]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ vars.HEROKU_APP_NAME }}
          HEROKU_EMAIL: ${{ vars.HEROKU_EMAIL }}
        run: heroku container:login

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Check for changes in backend
        run: |
          git diff --name-only HEAD~ HEAD | grep -q "packages/backend/"
          if [[ $? -ne 0 ]]; then
            echo "No changes detected in backend directory, skipping deployment."
            exit 0
          fi

     # - name: Login to Docker Hub (replace with your credentials)
      #  run: echo $DOCKER_USERNAME:$DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

      - name: Build Docker image
        run: |
          cd ./packages/backend
          docker-compose build

      - name: Tag the image for Heroku
        run: |
          cd ./packages/backend
          docker tag backend_api backendapi:backend_api

      - name: Push Docker image to Heroku container registry
        run: |
          cd ./packages/backend
          heroku container:push --app backendapi-git backendapi

      - name: Release the image to Heroku
        run: |
          cd ./packages/backend
          heroku container:release --app backendapi-git web
